// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowModalImmediatelyController from "./show_modal_immediately_controller"
application.register("show-modal-immediately", ShowModalImmediatelyController)

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import ScrollIntoViewController from "./scroll_into_view_controller"
application.register("scroll-into-view", ScrollIntoViewController)
